version: '3.8'

name: dv22caronnet_apit1

services:
  api:
    container_name: dv22caronnet_apit1
    ports:
      - '3000:3000'
    restart: unless-stopped
    command: start
    build:
      context: ./
      args:
        MONGODB_USER: ${MONGODB_USER}
        MONGODB_PASSWORD: ${MONGODB_PASSWORD}
        MONGODB_CLUSTER: ${MONGODB_CLUSTER}
